name: Bundles Build (Development Branches)

on:
  push:
    branches-ignore: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: "Build to test compileability"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.5
      with:
        submodules: true

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Build Artemis4J
      shell: bash
      working-directory: "bundles/edu.kit.kastel.sdq.eclipse.common.api/lib/artemis4j"
      run: mvn -P fatjar clean package -DskipTests

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -U -B package
