# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Eclipse Products

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
    tags: "v**"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11

    - name: Cache Maven packages
      uses: actions/cache@v2.1.6
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -U -B package --file pom.xml

    - name: Move Distributions
      run: |
        mkdir dist 
        mv releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-win32*.zip dist/Artemis_Windows.zip
        mv releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-linux*.zip dist/Artemis_Linux.zip
        mv releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-macosx*.zip dist/Artemis_MacOS.zip

    - name: Sign MacOS Eclipse Distribution
      env: 
        MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
        MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      run: |
        echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
        security create-keychain -p keychainpw build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p keychainpw build.keychain
        security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k keychainpw build.keychain
        security find-identity -p codesigning
        unzip dist/Artemis_MacOS.zip
        /usr/bin/codesign -s "kit-sdq/programming-lecture-eclipse-artemis" -fv Eclipse.app
        rm dist/Artemis_MacOS.zip
        ditto -c -k --sequesterRsrc --keepParent Eclipse.app dist/Artemis_MacOS.zip

    - name: Save Eclipse Distribution (Windows)
      uses: actions/upload-artifact@v2
      with:
        name: "Eclipse Distribution Windows"
        path: "dist/Artemis_Windows.zip"
    
    - name: Save Eclipse Distribution (Linux)
      uses: actions/upload-artifact@v2
      with:
        name: "Eclipse Distribution Linux"
        path: "dist/Artemis_Linux.zip"

    - name: Save Eclipse Distribution (MacOS)
      uses: actions/upload-artifact@v2
      with:
        name: "Eclipse Distribution MacOS"
        path: "dist/Artemis_MacOS.zip"
  
          
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          dist/Artemis_Windows.zip
          dist/Artemis_Linux.zip
          dist/Artemis_MacOS.zip
      
