name: Eclipse Artemis (Release)

on:
  push:
    tags: "v**"
  workflow_dispatch:

jobs:
  build:
    name: "Create release for new version"
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: true

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Build Artemis4J
      shell: bash
      working-directory: "bundles/edu.kit.kastel.sdq.eclipse.common.api/lib/artemis4j"
      run: mvn -P fatjar clean package -DskipTests

    - name: Build with Maven
      run: mvn -B -Pproducts package

    - name: Move Distributions
      run: |
        mkdir dists 
        mv releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-win32*.zip dists/Artemis_Grading_Windows.zip
        mv releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-linux.*.x86_64.zip dists/Artemis_Grading_Linux_x86_64.zip
        mv releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-linux.*.aarch64.zip dists/Artemis_Grading_Linux_aarch64.zip
        mv releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-macosx.*.x86_64.zip dists/Artemis_Grading_MacOS_x86_64.zip
        mv releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-macosx.*.aarch64.zip dists/Artemis_Grading_MacOS_aarch64.zip

    - name: Sign MacOS Eclipse Distribution (Grading)
      env: 
        MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
        MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      run: |
        rm -rf Eclipse.app
        echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
        security create-keychain -p keychainpw build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p keychainpw build.keychain
        security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k keychainpw build.keychain
        security find-identity -p codesigning
        unzip dists/Artemis_Grading_MacOS_x86_64.zip
        /usr/bin/codesign -s "kit-sdq/programming-lecture-eclipse-artemis" -fv Eclipse.app
        rm dists/Artemis_Grading_MacOS_x86_64.zip
        ditto -c -k --sequesterRsrc --keepParent Eclipse.app dists/Artemis_Grading_MacOS_x86_64.zip
        rm -rf Eclipse.app
        unzip dists/Artemis_Grading_MacOS_aarch64.zip
        /usr/bin/codesign -s "kit-sdq/programming-lecture-eclipse-artemis" -fv Eclipse.app
        rm dists/Artemis_Grading_MacOS_aarch64.zip
        ditto -c -k --sequesterRsrc --keepParent Eclipse.app dists/Artemis_Grading_MacOS_aarch64.zip 

    - name: Create sha256sum
      run: |
        for f in dists/*.zip; do shasum -a 256 $f > $f.sha256; done

    - name: Deploy Update Site
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        branch: gh-pages 
        folder: releng/edu.kit.kastel.sdq.eclipse.updatesite/target/repository
        clean: true 
        single-commit: true
          
    - name: GitHub Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          dists/Artemis_Grading_Windows.zip
          dists/Artemis_Grading_Linux_x86_64.zip
          dists/Artemis_Grading_Linux_aarch64.zip
          dists/Artemis_Grading_MacOS_x86_64.zip
          dists/Artemis_Grading_MacOS_aarch64.zip
          dists/Artemis_Grading_Windows.zip.sha256
          dists/Artemis_Grading_Linux_x86_64.zip.sha256
          dists/Artemis_Grading_Linux_aarch64.zip.sha256
          dists/Artemis_Grading_MacOS_x86_64.zip.sha256
          dists/Artemis_Grading_MacOS_aarch64.zip.sha256
