# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Eclipse Artemis (Release)

on:
  push:
    tags: "v**"
  workflow_dispatch:

jobs:
  build:
    name: "Create release for new version"
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3.0.2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Build with Maven
      run: mvn -U -B -Pproducts package

    - name: Move Distributions
      run: |
        mkdir dist 
        mv releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-win32*.zip dist/Artemis_Grading_Windows.zip
        mv releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-linux.*.x86_64.zip dist/Artemis_Grading_Linux_x86_64.zip
        mv releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-linux.*.aarch64.zip dist/Artemis_Grading_Linux_aarch64.zip
        mv releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-macosx.*.x86_64.zip dist/Artemis_Grading_MacOS_x86_64.zip
        mv releng/edu.kit.kastel.sdq.eclipse.grading.product/target/products/*-macosx.*.aarch64.zip dist/Artemis_Grading_MacOS_aarch64.zip
        mv releng/edu.kit.kastel.sdq.eclipse.student.product/target/products/*-win32*.zip dist/Artemis_Student_Windows.zip
        mv releng/edu.kit.kastel.sdq.eclipse.student.product/target/products/*-linux.*.x86_64.zip dist/Artemis_Student_Linux_x86_64.zip
        mv releng/edu.kit.kastel.sdq.eclipse.student.product/target/products/*-linux.*.aarch64.zip dist/Artemis_Student_Linux_aarch64.zip
        mv releng/edu.kit.kastel.sdq.eclipse.student.product/target/products/*-macosx.*.x86_64.zip dist/Artemis_Student_MacOS_x86_64.zip
        mv releng/edu.kit.kastel.sdq.eclipse.student.product/target/products/*-macosx.*.aarch64.zip dist/Artemis_Student_MacOS_aarch64.zip
        

    - name: Sign MacOS Eclipse Distribution (Grading)
      env: 
        MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
        MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      run: |
        rm -rf Eclipse.app
        echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
        security create-keychain -p keychainpw build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p keychainpw build.keychain
        security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k keychainpw build.keychain
        security find-identity -p codesigning
        unzip dist/Artemis_Grading_MacOS_x86_64.zip
        /usr/bin/codesign -s "kit-sdq/programming-lecture-eclipse-artemis" -fv Eclipse.app
        rm dist/Artemis_Grading_MacOS_x86_64.zip
        ditto -c -k --sequesterRsrc --keepParent Eclipse.app dist/Artemis_Grading_MacOS_x86_64.zip
        rm -rf Eclipse.app
        unzip dist/Artemis_Grading_MacOS_aarch64.zip
        /usr/bin/codesign -s "kit-sdq/programming-lecture-eclipse-artemis" -fv Eclipse.app
        rm dist/Artemis_Grading_MacOS_aarch64.zip
        ditto -c -k --sequesterRsrc --keepParent Eclipse.app dist/Artemis_Grading_MacOS_aarch64.zip
        
    - name: Sign MacOS Eclipse Distribution (Student)
      env: 
        MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
        MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      run: |
        rm -rf Eclipse.app
        echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
        unzip dist/Artemis_Student_MacOS_x86_64.zip
        /usr/bin/codesign -s "kit-sdq/programming-lecture-eclipse-artemis" -fv Eclipse.app
        rm dist/Artemis_Student_MacOS_x86_64.zip
        ditto -c -k --sequesterRsrc --keepParent Eclipse.app dist/Artemis_Student_MacOS_x86_64.zip
        rm -rf Eclipse.app
        unzip dist/Artemis_Student_MacOS_aarch64.zip
        /usr/bin/codesign -s "kit-sdq/programming-lecture-eclipse-artemis" -fv Eclipse.app
        rm dist/Artemis_Student_MacOS_aarch64.zip
        ditto -c -k --sequesterRsrc --keepParent Eclipse.app dist/Artemis_Student_MacOS_aarch64.zip   

    - name: Deploy Update Site
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        branch: gh-pages 
        folder: releng/edu.kit.kastel.sdq.eclipse.updatesite/target/repository
        clean: true 
        single-commit: true
          
    - name: GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          dist/Artemis_Grading_Windows.zip
          dist/Artemis_Grading_Linux_x86_64.zip
          dist/Artemis_Grading_Linux_aarch64.zip
          dist/Artemis_Grading_MacOS_x86_64.zip
          dist/Artemis_Grading_MacOS_aarch64.zip
          dist/Artemis_Student_Windows.zip
          dist/Artemis_Student_Linux_x86_64.zip
          dist/Artemis_Student_Linux_aarch64.zip
          dist/Artemis_Student_MacOS_x86_64.zip      
          dist/Artemis_Student_MacOS_aarch64.zip