name: Spotless Style Check

on:
  push: 
  pull_request:
    types: [opened, synchronize, reopened]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  style-check:
    name: "Check codestyle with Spotless"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.6.0
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
      
    - name: Check with Spotless
      run: mvn clean spotless:check
      
      

