name: Spotless Style Check

on:
  push: 
  pull_request:
    types: [opened, synchronize, reopened]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  style-check:
    name: "Check codestyle with Spotless"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
        submodules: true

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Build Artemis4J
      shell: bash
      working-directory: "bundles/edu.kit.kastel.sdq.eclipse.common.api/lib/artemis4j"
      run: mvn -P fatjar clean package -DskipTests
      
    - name: Check with Spotless
      run: mvn clean spotless:check
      
      

