# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Update Site

on:
  push:
    tags: "v**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -U -B package

    - name: Deploy GH Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        BRANCH: gh-pages 
        FOLDER: releng/edu.kit.kastel.sdq.eclipse.updatesite/target/repository
        CLEAN: true 
   
